### ISSUE TITLE
Sample for method with required oneof wouldn't work

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#238]
For example, `SubscriberClient.Seek`:

```csharp
// Create client
SubscriberClient subscriberClient = SubscriberClient.Create();
// Initialize request argument(s)
SeekRequest request = new SeekRequest
{
    SubscriptionAsSubscriptionName = new SubscriptionName("[PROJECT]", "[SUBSCRIPTION]"),
};
// Make the request
SeekResponse response = subscriberClient.Seek(request);
```

In reality, you need to specify a `Time` or `Snapshot` - but we don't have support for request oneofs yet. Updating the "build a request" sample should be part of the work for this.

**Comment by chrisdunelm** [comment]
@amanda-tarafa Is this issue still relevant with your snippet changes?

**Comment by amanda-tarafa** [comment]
Yes, I haven't made changes on sample code generation per se.

If it's not a fast fix that you can quickly do, maybe assign to me.  I will have to look at sample request creation as part of SnippetGen work anyway.

**Comment by chrisdunelm** [comment]
I _think_ this issue was first filed on the monolithic generator.
So it's not quite accurate for this micro-generator. The issue here is that _all_ oneof fields are generated into the snippet request object: [Example from pubsub](https://github.com/googleapis/google-cloud-dotnet/blob/735f21739910b79b520de6e1eca4599778aad852/apis/Google.Cloud.PubSub.V1/Google.Cloud.PubSub.V1.Snippets/SubscriberServiceApiClientSnippets.g.cs#L1662).
