### ISSUE TITLE
Consider ServiceMetadata for mixins

### ISSUE THREAD

**Issue by jskeet** [googleapis/gapic-generator-csharp#499]
It's possible that mixins (LRO, IAM etc) might need different metadata for different APIs, e.g. if both Google.Cloud.Xyz.V1 and Google.Cloud.Abc.V1 support LRO, but one support REST transport and the other doesn't, how do we currently handle that? (I suspect we don't get it right...)

**Comment by jskeet** [comment]
Additionally, this may affect enum encoding.

Currently we create a client based on CallInvoker, which means the gRPC adapter has already been "fixed". Any CallInvoker-specific behavior will be shared by the mixin.

**Comment by amanda-tarafa** [comment]
My two not so knowledgeable cents:

1. Mixins should be used with the same transport that was selected for the API.  Mixins are an implementation detail from the point of view of the user.
2. For point 1 to hold we need to make sure (manually, as we know exactly which APIs can be mixins) that all mixins support both transports. Since we are sharing the CallInvoker, the mixing will use the same transport as the main service client.
3. If we ever get a mixin that supports only one transport, then I'd say that we are fine to fail when the mixin unsupported transport is selected for the main service client (instead of attempting to use a different transport for the mixin). At that point we'd need to share some transport information with the service client and decide when to fail. But I'd say, maybe, we cross that bridge if we ever get there?

**Comment by jskeet** [comment]
I think all of this can be punted on for a little while, other than perhaps the numeric enum flag, but I want to make sure we don't forget about it :)

**Comment by jskeet** [comment]
Closing as I believe we fixed this a little while ago - I know I've had mixins working for REGAPIC APIs, and I don't know of anything that still needs doing.
